### ISSUE TITLE
Pirate Radio

### ISSUE THREAD

**Issue by yfr** [eminentspoon/phatbeat-node#1]
Hey thanks for the module. Looks great so far.

I just got my pirate radio from pimoroni but i'm a very beginner at all this GPIO and LED thing. You say in the README that you have set up the pirate radio with the phatBeat. Do you have some example code especially for that? 
I would love to use the volumio audio player with this setup. I can't get the volume control to work. Start and stop is fine

Is it possible to have the LED blink like an EQ?

**Comment by eminentspoon** [comment]
Hey,

The functionality accessible via this module is simply control of the LEDs and buttons directly (for the purposes of custom projects). If you want the ability to have the LEDs show like an EQ meter, I believe that Pimoroni have written and included an ALSA plugin in their default software package for the Pirate Radio and I remember testing it with VLC streams when I first got it (which seemed to work fine). The default software ties the buttons and EQ stuff into the ALSA architecture but I never tried with volumio. Might be worth checking their forum out or having a look [here](https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-phat-beat) for their default software.

Best of luck! I really need to dust mine off and have another play with it, too many projects, too little time!

**Comment by yfr** [comment]
Thanks a lot. I've already contacted the pimoroni team for the alsa plugin
and waiting if they can help me. I really love the volumio setup and would
definitely love some blinking lights on it :)
